# Generated by Django 4.1.3 on 2023-01-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_image_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('useremail', models.CharField(max_length=300)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
